### ISSUE TITLE
Make snippets AST aware

### ISSUE THREAD

**Issue by karrtikr** [microsoft/python-language-server#1080]
@its-dhung commented on [Wed May 08 2019](https://github.com/microsoft/vscode-python/issues/5583)

## Environment data

- VS Code version: 1.29.1
- Extension version (available under the Extensions sidebar): 2019.1.0
- OS and version: macOS 10.14.4
- Python version (& distribution if applicable, e.g. Anaconda): 2.7.10
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: N/A

## Expected behaviour

When triggering completions, I would expect snippets that are not relevant for the current AST context to not be shown.

## Actual behaviour

Snippets are shown in cases where the insertion of the snippet would result in invalid code.

## Steps to reproduce:

Consider this piece of code, where `$` denotes current cursor position.

```python
numer = 1000
denom = 10

quotient = numer / de$
```

This results in snippets for `def` being shown:

![image](https://user-images.githubusercontent.com/3752225/57395610-67553980-717d-11e9-96e7-6eb61e899eea.png)

Is it possible to hide irrelevant snippets in cases like this?

---

@karrtikr commented on [Tue May 14 2019](https://github.com/microsoft/vscode-python/issues/5583#issuecomment-492434749)

I am not sure if that's feasible or not. Moving this issue to double-check.

**Comment by jakebailey** [comment]
We don't implement snippets; the extension is the one providing those, while the other completion items (`delattr`, `denom`) are provided by us.

I don't think this is anything we can affect, since we don't provide the snippets. See: https://github.com/microsoft/vscode-python/blob/2312c3e88d0331cbff1ab32e3540841ad27daa77/snippets/python.json#L163

I think any sort of context awareness would need to be added to VSC first, since those snippets are static/declarative and don't appear to have any sort of pattern to provide any; for those `def` snippets in particular, the simplest solution would be to only allow them if the entire line is whitespace already, but I have not investigated that far.

Closing, as there's nothing we can do on this from the LS.

**Comment by MikhailArkhipov** [comment]
Well we could expose some sort of custom validation point like `python/canInsertSnippet` but extension would need to take the first cut.
