### ISSUE TITLE
Reloading modules leaks memory

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#109]
Clone [dups](https://github.com/linuxwhatelse/dups).
Open it
Open few files, do some random go to definitions.
Leave product inactive

Observe RAM growth and some odd module reloading

![image](https://user-images.githubusercontent.com/12820357/45721234-10eaaa80-bb5c-11e8-89bd-1c1bba988e83.png)

**Comment by heyakyra** [comment]
Found this bug via https://github.com/Microsoft/vscode-python/issues/2594

Is there a workaround for this? I'm basically blocked at work because all 16G ram + 8G swap gets completely consumed after half an hour of editing

**Comment by MikhailArkhipov** [comment]
@heyakyra - you are probably hitting https://github.com/Microsoft/python-language-server/issues/193. This one is not too bad.

**Comment by MikhailArkhipov** [comment]
Depends on https://github.com/Microsoft/python-language-server/issues/209

**Comment by jakebailey** [comment]
@GinRyan Unless you can see in your output "reloading modules" repeated while memory usage grows, your issue is likely unrelated to the original bug reported here. If you believe you have an issue we can reproduce, I'd suggest making a new issue with more information instead of commenting on older issue like this one and #109.
