### ISSUE TITLE
Support 3.8 fstring debug syntax in parser

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1102]
Python 3.8 comes with a new fstring feature:

```python
print(f"{name=}")
print(f"{name =}")
print(f"{name = }")
print(f"{foo.bar()=}")
# etc
```

Is equivalent to writing:

```python
print(f"name={repr(name)}")
print(f"name ={repr(name)}")
print(f"name = {repr(name)}")
print(f"foo.bar()={repr(foo.bar())}")
# etc
```

We don't particularly need to know about the string that gets printed, but we'll have to handle the extra `=` at the end in 3.8+.

Note that these can be combined with `!` stuff, so:

```python
print(f"{foo=!s}")
```

https://bugs.python.org/issue36817

**Comment by incognitoRepo** [comment]
greetings!
glad i found this thread because i've had a unresolved issue with python error analysis in vscode. 
with this particular example, i'll get the red squiggles under the equal sign + the problems panel will list a problem for each use.
the info i can get from the problems panel (r-click copy) is cryptic. the important `values()` seem to be "_generated_diagnostic_collection_name_#3", "parser-16", "unexpected token '='". 
i've been checking vscode/vscode-python repos occasionally but the issues get closed without solution. i may be mistaken but i think i rmbr even reading someone state that "parser-16" is unassociated with vscode-python. 
here is what i know so far (having search this repo, as well):
parser-16 is a python-language-server "thing"[1].
i still get the "unexpected token" error with "python.linting.enabled" set false.
there are others who seem to be confused about what can/can't be done to minimize workflow disruptions[2]

i'm assuming this error cannot be ignored, but please correct me if i am wrong. 

thanks! really do like this editor 👍

[1]: https://github.com/microsoft/python-language-server/issues/1350#issue-470456083
[2]:https://github.com/Microsoft/vscode/issues/72997#issue-438059787

**Comment by jakebailey** [comment]
Can you please post a screenshot? Is this related to the extra `=` as mentioned in this issue?

**Comment by jakebailey** [comment]
https://docs.python.org/3.8/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging

**Comment by incognitoRepo** [comment]
ty jake, i apologize i had a family matter. i just checked my python code to get u a screenshot. but, as this thread shows, its all working now. still my main editor 💯
