### ISSUE TITLE
Auto completion of private methods

### ISSUE THREAD

**Issue by lauevrar77** [microsoft/python-language-server#1154]
Hello, 

I'm writing this issue for something that may be an error in the auto completion (it may also be a design choice) but when I create `__something()` private methods (or attributes), they are auto completed to `_ClassName__something()`. 

I known python internally do this transformation at runtime however, the behavior that I expected is to have this method (or attribute) auto-completed to `__something()`.

Here is an example : 
<img width="385" alt="Capture d’écran 2019-06-03 à 05 51 56" src="https://user-images.githubusercontent.com/6632473/58774990-070eb780-85c4-11e9-9196-add6c80332a8.png">

**Comment by jakebailey** [comment]
I found this the other day, you beat me to reporting it. 😃

**Comment by MikhailArkhipov** [comment]
Here when class is analyzed, LS handles class data member declarations, then the constructor. In this case constructor declares `remote_id` via `self.remote_id = remote_id`, which then conflicts with `def remote_id`. We'd need to see what exactly class members are in this case. Generally current code assumes that all class members have unique names.

**Comment by lauevrar77** [comment]
I don't think it is linked to a conflict of name here. Them problem also appear with simpler examples : 

<img width="799" alt="Capture d’écran 2019-06-03 à 07 22 51" src="https://user-images.githubusercontent.com/6632473/58777872-a8036f80-85d0-11e9-9463-04f31d4a3254.png">

In my example remote_id became a property setter afterward.

**Comment by MikhailArkhipov** [comment]
This looks by design. Parser generates this name according to
https://docs.python.org/3/tutorial/classes.html#private-variables

where `__foo` becomes `_ClassName__foo`.

_Any identifier of the form __spam (at least two leading underscores, at most one trailing underscore) is textually replaced with _classname__spam, where classname is the current class name with leading underscore(s) stripped. This mangling is done without regard to the syntactic position of the identifier, as long as it occurs within the definition of a class_.

https://stackoverflow.com/questions/1301346/what-is-the-meaning-of-a-single-and-a-double-underscore-before-an-object-name

**Comment by lauevrar77** [comment]
I know that python use this renaming convention to make private attributes or methods private at runtime (dynamic behavior) but during the implementation (static behavior), isn't it more sound to auto-complete with the approriate (static behavior) value ?

**Comment by MikhailArkhipov** [comment]
Yes, agreed. What needs to change is 
- presentation layer, i.e. show original, unmangled name.
- linter, so it does not confuse mangled and unmangled names.
