### ISSUE TITLE
NRE in SymbolCollector.AddProperty

### ISSUE THREAD

**Issue by jakebailey** [microsoft/python-language-server#1201]
```
Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.AddProperty(FunctionDefinition, IPythonType, Boolean) in Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 170
Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.TryAddProperty(FunctionDefinition, IPythonType) in Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 158
Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.AddFunctionOrProperty(FunctionDefinition) in Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 101
Microsoft.Python.Analysis.Analyzer.Symbols.SymbolCollector.Walk(FunctionDefinition) in Analysis\Ast\Impl\Analyzer\Symbols\SymbolCollector.cs:line 77
Microsoft.Python.Parsing.Ast.FunctionDefinition.Walk(PythonWalker) in Parsing\Impl\Ast\FunctionDefinition.cs:line 197
```

Not sure what could be null at line 170, though. Maybe it's getting optimized and `fd` is null and is breaking at `fd.Name`.

**Comment by MikhailArkhipov** [comment]
`null` function names do happen, but walker checks it in `Walk`:
```cs
if (!string.IsNullOrEmpty(fd.Name)) {
    AddFunctionOrProperty(fd);
```
So I guess, _eval or something in `_eval.GetLocationOfName(fd)`

**Comment by jakebailey** [comment]
Was the same as #1219, I believe.

**Comment by jakebailey** [comment]
Didn't go away.

**Comment by MikhailArkhipov** [comment]
- Walking AST, walker didn't crash so `FunctionDefinition` is valid. That's line 197. 
- Line 77 can only get called when `if (!string.IsNullOrEmpty(fd.Name))` so both `fd` and `Name` are valid.
- 101 and 158 are just passing stuff down
- 177 is `_eval.GetLocationOfName(fd)`.

So either a) `_eval` is null - which is unlikely, we'd crash way earlier and besides, it is readonly and
```cs
_eval = eval ?? throw new ArgumentNullException(nameof(eval));
```

this means `GetLocationOfName` is inlined and the issue is there. `fd` is not null and if it was, then `GetLocationOfName` would throw in
```cs
node = node ?? throw new ArgumentNullException(nameof(node));
```
so what IS null is the `NameExpression` in `fd` which may happen in
```python
def (a, b, c)
```
