### ISSUE TITLE
__spec__ missing in module scope

### ISSUE THREAD

**Issue by janosh** [microsoft/python-language-server#1264]
## Environment data

- VS Code version: 1.35.1
- Extension version: 2019.6.22090
- OS and version: macOS 10.14.4
- Python version: 3.6.7
- Type of virtual environment: conda
- Jedi or Language Server: language server

## Actual behavior

![spec](https://user-images.githubusercontent.com/30958850/60385615-f0546700-9a82-11e9-99b9-5b1444d5d0e8.png)

Using `__spec__` raises a problem (undefined variable).

## Expected behavior

Reading other global attributes like `__name__` doesn't so this seems inconsistent at first glance. Any reason for this?

**Comment by jakebailey** [comment]
We have a list of variables that we define in scope of a module, `__spec__` is likely just missing. I think declaring it would unfortunately make every module analysis dependent on whatever module defines `ModuleSpec`, which is `importlib`.

**Comment by janosh** [comment]
> I think declaring it would unfortunately make every module analysis dependent on whatever module defines `ModuleSpec`, which is `importlib`.

Just so I understand, why would that be a problem?

**Comment by jakebailey** [comment]
From our end, we'd need to analyze `importlib`, which requires analyzing everything `importlib` imports, and so on. It would just mean every analysis (even on code without any imports at all) would require this to happen, as every module would have a `__spec__`, plus the added issue of that being a circular problem (every module would have a `__spec__` which can only be produced by analyzing another module, which itself is supposed to have a `__spec__`).

We'd sooner write a custom type to take its place rather than trying to get the "real" spec. An even quicker fix just to drop the warning would be to say that it's `object`.

**Comment by janosh** [comment]
Another "quick" fix would be to resolve #264. Then you could do
```py
logger = get_logger(__spec__.name, log_dir)  # noqa: F821
```

**Comment by jakebailey** [comment]
Note that you can already disable any of the warnings we put out (other than syntax errors), for example:

```json
"python.analysis.disabled": ["undefined-variable"]
```

But yes, something per-line would be good. Note that we don't have any mapping from pylint/flake8/etc "codes" to our own, so that'd be something on top of being able to disable diagnostics per-line.

**Comment by janosh** [comment]
> Note that we don't have any mapping from pylint/flake8/etc "codes" to our own, so that'd be something on top of being able to disable diagnostics per-line.

Yeah, I thought there might be some extra work there. But it's just icing on the cake, anyway. A code-insensitive, but per-line `# noqa` directive already provides most of the value.

**Comment by MikhailArkhipov** [comment]
In `DeclareBuiltinVariables` need to add `__spec__`
