### ISSUE TITLE
Analysis order based on import graph

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/python-language-server#135]
`GetEntriesThatImportModule` is required to queue dependent modules for reanalysis when the dependency has changed. If dependent module analysis isn't finished, `GetEntriesThatImportModule`  skips it.

**Comment by MikhailArkhipov** [comment]
I am going to rename it since we should not need to reanalyze - if we know the import order based on graph for #12, #71 we should just analyze in order from root to leaves. Which will also fix #163

**Comment by lostmsu** [comment]
I experience an issue where in some cases, `ClassInfo.Bases[0]` keeps pointing to empty analysis set, when the code looks like this:

```python
from module import BaseClass

class DerivedClass(BaseClass):
  ...
```

After analysis is finished, I can query variable `BaseClass` in `module`, and it will show `user class ...`. However, `DerivedClass.Bases[0]` is still pointing to an instance of `AnalysisSetEmptyObject`.

The above import for the first time is analyzed before `BaseClass`, however, `DerivedClass` bases are never reanalyzed after that.

I wonder, if this is the root cause for this behavior.

**Comment by MikhailArkhipov** [comment]
#432
