### ISSUE TITLE
Improper Interpreter

### ISSUE THREAD

**Issue by geauxtigers** [microsoft/python-language-server#1480]
I have a project run under WSL where Python 3.6 is installed as a venv.  In VS Code, the venv is selected appears correctly specified in `settings.json` as:

`"python.pythonPath": "./venv/bin/",`

I first noticed the issue as specified in [this issue](https://github.com/microsoft/python-language-server/issues/1131) which references the script:

![Capture](https://user-images.githubusercontent.com/8951542/63651861-2595d200-c71f-11e9-9c80-aa7c2f5efb02.PNG)

The script above will execute perfectly fine from the VS Code terminal (using the venv specified in the settings file) but when run using CodeRunner and the Python Extension, the above output is displayed in the code pane.  

I inserted a version check and commented out the print line.  The version of Python used in the coderunner workflow was the system version of 2.7 as shown below (the venv selection can be seen in the statusbar).  Is this a bug or is there some other setting that I am missing?

![Capture](https://user-images.githubusercontent.com/8951542/63651983-53c7e180-c720-11e9-95ce-8b3fda1deab9.PNG)

My system is as follows:

**Windows 10**
Version 1803 OS Build 17134.950

**WSL**
Distributor ID: Ubuntu
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic

**VS Code**
Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Extensions WSL-Installed**
Name: Code Runner
Version: 0.9.14

Name: Git History
Version: 0.4.6

Name: GitLens — Git supercharged
Version: 9.9.3

Name: Heroku
Version: 1.2.6

Name: Python
Version: 2019.8.30787

Name: VS Color Picker
Version: 1.0.0

**Comment by MikhailArkhipov** [comment]
This problem appears to be unrelated to the language server. LS does not run your code and generally does not even know that is is running in VS Code. LS is a static code analyzer that responds to messages conforming to common language server protocol. It is used in VS Code, Emacs, Vim, Sublime the same way.  Neither LS selects Python interpreter - path to the interpreter is provided by the host/client app.

You may want to open an issue in Python Extension https://github.com/Microsoft/vscode-python since it appears about Python interpreter selection.
