### ISSUE TITLE
[Feature Request] Make language server able to operate while executing a cell in jupyter 

### ISSUE THREAD

**Issue by aduriseti** [microsoft/python-language-server#1525]
Not 100% sure - but it seems to me that when I execute a cell in the jupyter extension it suspends language server analysis.

If I am right - is there a reason these are not completely separate processes?  It would improve usability for me greatly.

**Comment by MikhailArkhipov** [comment]
LS can be same process or multiple. It is up to the client application to decide. For example, in Visual Studio it would be multiple since solution can contain multiple projects each on its own version of Python and set of libraries. So I'd recommend opening issue in the Python extension since data science part of it controls how it uses the LS. LS in fact, does not even know it is running in VS Code.

**Comment by MikhailArkhipov** [comment]
I am going to close this issue as it is not related to the LS since LS does not know about its client app and has no means to control its behavior. Thanks.
