### ISSUE TITLE
Unresolved local imports

### ISSUE THREAD

**Issue by janosh** [microsoft/python-language-server#1615]
![broken-local-imports](https://user-images.githubusercontent.com/30958850/66041338-8b8d2a80-e511-11e9-8fa8-c04ce510fe02.png)

Following the advice in the [troubleshooting guide](https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings), I tried fiddling around with
```json
"python.autoComplete.extraPaths": [
  "./", "./src"
]
```
to no avail. In all cases, doing
```py
import sys
print(sys.path)
```
does not include the workspace directory in a project I hadn't opened in two weeks but which used to work fine before then.

Any changes during that time period which might have caused this? Also, how to troubleshoot this further?

## Environment data

- VS Code version: 1.38.1
- Extension version: nightly insiders
- OS and version: macOS 10.14.6
- Python version: 3.6.7
- Type of virtual environment: miniconda
- Jedi or Language Server? Language Server

**Comment by jakebailey** [comment]
Could you include some info from: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#filing-an-issue

Mainly, I'd be interested to see the folder layout of the folder you've opened in VS code, to verify that `src` is inside it. Note that if you're using multi-root workspaces rather than open folder, you might have some issues (#1599).

**Comment by janosh** [comment]
It's a single-root workspace. Here's the directory structure.

![dirs](https://user-images.githubusercontent.com/30958850/66080420-fd8b6100-e55d-11e9-849f-9781a1d34e63.png)

Are you also interested in trace logging or the Python output panel?

**Comment by jakebailey** [comment]
I see what's going on here. You're using a src directory, but importing from `src.`, which is pretty unusual.

If you really need to import things with a `src.` prefix (the norm would be to make `src` the import root, and do something like `import utils.evaluate`), then I believe it should work if you drop all of the extraPaths configuration, and then set the following:

```json
"python.analysis.autoSearchPaths": false
```

**Comment by jakebailey** [comment]
Most people who have a `src` directory do not import with `src.`, so the language server will detect when `src` is not a package (no `__init__.py` in `src`) and automatically use `src` as an import root, but your project doesn't follow that.

**Comment by jakebailey** [comment]
My comments above didn't require removing `src.` from everything, just some configuration change. With extraPaths removed and autoSearchPaths disabled, do the `src.` prefixed imports resolve? (autoSearchPaths aren't documented in the extension yet, but the option should still work.)

The behavior would have changed due to #1440. Most users with a `src` directory do not have imports that look like `import src.something`, so we modified the default behavior to consider a `src` directory to be an import roof if present by default.

The `src` folder-using projects I've seen do not require `import src.`, but instead import with `src` as a search path. How are you executing your code such that that's required?

**Comment by janosh** [comment]
Ah, you're right, adding `  "python.analysis.autoSearchPaths": false` indeed makes local imports resolve even though it's labelled as "Unknown Configuration Setting". Thanks for that!

> How are you executing your code such that that's required?

[This is the project in question](https://github.com/janosh/thermo). It's basically just Python files using VS Code code cells (`#%%`) which are executed in the interactive window.

**Comment by jakebailey** [comment]
That's interesting. Does using a `.env` file with `PYTHONPATH=./src` and dropping all of the configuration and `src.` import prefixes also work in that scenario?

**Comment by janosh** [comment]
Yeah, I tried that before. It does solve the imports in VS Code but I would then have to load `.env` in every notebook to make the imports work when executing the notebooks, no?

**Comment by jakebailey** [comment]
I'm not entirely certain. I'd have thought that the `.env` file would be loaded when the Jupyter process is launched, but I'm not completely familiar with that part of the extension. @rchiodo or @DonJayamanne might know better about how `.env` does/doesn't work in that situation.

Trying to get the LS and the extension (plus the tools it runs) in line when it comes to search paths is certainly a goal we're working on, it's just difficult since every tool works a little bit differently.

For now, I think that disabling `autoSearchPaths` should fix your scenario. Sorry about the breakage, I knew there would be a little fallout (even if most `src` users benefit).

**Comment by jakebailey** [comment]
Closing, since disabling the new heuristic fixed it (and that's an expected outcome of adding it).

**Comment by janosh** [comment]
@jakebailey Just noticed that `python.analysis.autoSearchPaths` is still undocumented. Would you accept a PR to add that?

**Comment by jakebailey** [comment]
It depends what you mean; the greying-out that happens in VS Code means the setting isn't present in the extension's `package.json`, which is another repo. We have a number of settings we don't document there quite yet (there's an ongoing discussion about how to even out search path handling between everyone consistently, so we haven't really touched the existing setup).

**Comment by janosh** [comment]
Yeah, I meant adding it to the Python extension's `package.json`. But if it's still a WIP, I don't mean to push changes that might have to be reverted.
