### ISSUE TITLE
IntelliSense stops working when certain python files open. 

### ISSUE THREAD

**Issue by noahschumacher** [microsoft/python-language-server#1638]
IntelliSense appears to be working fine when working on one .py file but when another .py file is opened IntelliSense and all autocomplete will be disabled. The files that seem to disable IntelliSense are in a git repo while files not in a git repo work fine. 

## Environment data

- VS Code version: 1.38.1
- OS and version: 10.14.6 macOS
- Python version (& distribution if applicable, e.g. Anaconda): 3.7 Anaconda
- Type of virtual environment used: conda

## Expected behaviour

![image](https://user-images.githubusercontent.com/26905830/66334036-16dd3600-e8ed-11e9-916e-9c254711ef06.png)

## Actual behaviour

No autocomplete suggestions.

**Comment by jakebailey** [comment]
I've seen gitlens mentioned a few times in other issues in our repos. Does it do anything with the completion list such that it'd break things?

Note that we don't offer some features when working on files outside of the workspace, so if you were to open a random file elsewhere, completion may not work.

**Comment by noahschumacher** [comment]
Hm interesting point Jake. I am not an expert with GitLens but it does have a fair amount of Git suggestion/info windows that do pop up when moving the cursor through code. Potentially this was taking precedence over IntelliSense/autocomplete? Just speculating here.

**Comment by jakebailey** [comment]
It's possible. Theoretically, it should only be adding things to the completion list, not completely overriding it, but I don't know how it's implemented. My guess is that since it's a VS Code extension, they're doing some shenanigans which override other plugins, which we wouldn't really be able to handle (we just give VS Code, the client, a list of options, and its up to it to display things).

**Comment by jakebailey** [comment]
I'm going to close this, since uninstalling GitLens fixes the issue. The language server only gives the editor the completion choices to show, and can't control what the editor does with them or extensions which override other extensions. It's not clear to me that there's anything we could fix to help this scenario.
