### ISSUE TITLE
Why is `Mock: Any` necessary in `mock.pyi`?

### ISSUE THREAD

**Issue by cjlint** [microsoft/python-language-server#1714]
I noticed that `Mock` objects did not have autocomplete results for me. For example:

```
import mock

a = mock.Mock()
a.
```

I found that if I uncommented this line: https://github.com/microsoft/python-language-server/blob/7ec9561deeb1b53cb3e24e996a5229a1015fe886/src/Analysis/Ast/Impl/Typeshed/third_party/2and3/mock.pyi#L43 autocompletion in the above snippet started working. What is the purpose of specifying `Mock: Any` at all, is it safe to uncomment or even remove the line in a PR?

**Comment by jakebailey** [comment]
This is a checkout of another repo which provides type stubs, here: https://github.com/python/typeshed/blob/master/third_party/2and3/mock.pyi

We can't exactly modify this since it's not our code (licensing stuff), but it is strange that it'd be mocked as essentially "nothing". Our code assumes that the stubs provide better information than the real code (otherwise they wouldn't have been written), so this sort of violates that assumption.

We might be able to tweak our stub merge algorithm to take the analyzed type over the stub type if the stub defines a variable to be `Any`, but it might also regress something else. Would need some testing.

**Comment by jakebailey** [comment]
Upstream has changed this definition so this issue would covered if we do #1371.
