### ISSUE TITLE
lightgbm parameters intellisence Unsupport

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/python-language-server#1741]
![image](https://user-images.githubusercontent.com/44701446/68078833-89243600-fe19-11e9-85ff-a0260095fe67.png)

The python language server fails to show the key parameters of lightgbm.

**Comment by MikhailArkhipov** [comment]
Depends what is expected. Code analysis is not looking into specific file structure in order to determine return from file contents, if that is what you mean.

`np.load` returns `NpzFile` object. With https://github.com/microsoft/python-language-server/pull/1686 I get
![image](https://user-images.githubusercontent.com/12820357/68078886-e201b900-fd9c-11e9-8a09-0ea81bb15c31.png)
