### ISSUE TITLE
Failed parsing matmul operator

### ISSUE THREAD

**Issue by odiak** [microsoft/python-language-server#1825]
## Environment data

- Language Server version: 0.4.127.0
- OS and version: macOS 10.14.6
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.0

## Expected behaviour

Parser should be able to parse this code:

```python
a = (
    A
    @ B
)
```

## Actual behaviour

It causes parser error `unexpected token '<newline>'` at end of 2nd line.

Note that this happened only with `@` operator. (No parse error with `+` or `*` instead of `@`.)

**Comment by MikhailArkhipov** [comment]
Will look into this...

**Comment by MikhailArkhipov** [comment]
The underlying issue is that `@` comes as 'At' token since during tokenization it is unclear if @ is an attribute or part of an expression. Tokenizer drops newlines with regular operators but in this case they remain so `1\n+2` is `constant operator constant` while `1\n@ 2` is `constant newline at constant` and the number of line breaks is not limited to just one so simple lookahead is insufficient.

**Comment by odiak** [comment]
I'm grad to be fixed! 😄
