### ISSUE TITLE
Where is the code for the latest VSCode release of MLSP

### ISSUE THREAD

**Issue by danzvara** [microsoft/python-language-server#1826]
Hi there!

I have a quick question - how does a version number reported in VSCode relate to a code release? 
For example, the latest release here is said to be 0.2, but VSCode reports to use 0.4.114, which I cannot find anywhere.

Thanks!

**Comment by MikhailArkhipov** [comment]
Language server version is displayed in the Output window at startup. It is unrelated to the version of extension as two products are released separately. Extension downloads latest from stable channel unless specified otherwise. We publish updates pretty frequently and don’t maintain github releases.

**Comment by jakebailey** [comment]
If you mean https://github.com/microsoft/python-language-server/releases, we haven't been tagging releases; the version number is closer to a build number. https://github.com/microsoft/python-language-server/wiki/Versioning-and-download-channels
