### ISSUE TITLE
suggestion trigger

### ISSUE THREAD

**Issue by byehack** [microsoft/python-language-server#1830]
i select a function name of suggestions window and for trigger it i want to use "(" instead "enter"/"tab".  like < idle >.

**Comment by ericsnowcurrently** [comment]
@byehack, sorry for the confusion.

**Comment by MikhailArkhipov** [comment]
It is trivial to add the option but the `python.autoComplete.addBrackets` should be set to false since otherwise you'll get `print(())`. Per LSP when completion character is typed then the entry is accepted and the completion character is added. When `python.autoComplete.addBrackets: true`, the entry is a snipped as in `print($0)` so you get double braces. Side effect of ``python.autoComplete.addBrackets: false` is that you get `print()` when completing with `(` but you'll get plain `print` when completing with tab or space.

**Comment by jakebailey** [comment]
microsoft/vscode-python#10306

**Comment by jakebailey** [comment]
Per https://github.com/microsoft/vscode-python/issues/10306#issuecomment-604103769, I don't think we're going to be doing this at this time. Closing for consistency with the extension.
