### ISSUE TITLE
Docstring missing for matplotlib.pyplot.plot

### ISSUE THREAD

**Issue by faultdiagnosistoolbox** [microsoft/python-language-server#1879]
I use VSCode and the python extension for my everyday coding. Typically I use it in REPL mode, connecting to a Jupyter session. I am very happy with this environment.

One thing that I wonder about is they way help popups work.  I'm not sure if it is a misconfiguration on my part or if it is supposed to work that way,

I have attached a screenshot of a minimal example, where the documentation for plt.plot() is very limited in the editor window; but help(plt.plot) at the console gives the full information. I get full documentation for some, but not all commands. The same example in, e.g., Spyder gives full information.

Misconfiguration or feature? I run the latest version of VSC and the extension on a Mac/Catalina.

<img width="1829" alt="Screen Shot 2020-01-18 at 20 50 29" src="https://user-images.githubusercontent.com/26159583/72669786-42b49f80-3a36-11ea-85c8-d349104ba112.png">

**Comment by jakebailey** [comment]
The info on the left is determined statically, the info on the right is determined at runtime. Due to the way this library (and many others) are implemented, it might be difficult (or nearly impossible) to determine the docstrings without executing the code, something we don't want to do. Jupyter is a live Python process, and all of its completion, docstrings, etc, are live running code.

If you jump to the function's definition (which should work), you should see the code that the language server is able to look at. I would expect the documentation to be missing.

**Comment by jakebailey** [comment]
See here: https://github.com/matplotlib/matplotlib/blob/63cbb606468f3a3cda1989c8a44e3c357037cc3b/lib/matplotlib/pyplot.py#L2583

The docstring is added at runtime by a decorator which copies the docstring from some other type to the function:

https://github.com/matplotlib/matplotlib/blob/63cbb606468f3a3cda1989c8a44e3c357037cc3b/lib/matplotlib/docstring.py#L99

**Comment by faultdiagnosistoolbox** [comment]
Ah, OK. Now I understand the problem. Thanks again.

**Comment by MikhailArkhipov** [comment]
Closing since static code analysis is unable to determine dynamic assignments at runtime. Possible solution is to have package declare it statically, helping editors. In any case, LS can't do much here.
