### ISSUE TITLE
Unresolved import of files located at the root of the workspace.

### ISSUE THREAD

**Issue by abarabakuhatsu** [microsoft/python-language-server#1945]
# Unresolved import of files located at the root of the workspace.

Unresolved import warning appears when importing from workspace root file.
If I set extraPaths, no Unresolved import warning is displayed for in file not rooted at the workspace root.

## Expected behaviour
Files located at the root of the workspace can import files in the directory without warning

## Actual behaviour

Files located at the root of the workspace warn about importing from a directory

![2020-03-17_15h30_54](https://user-images.githubusercontent.com/43849035/76829104-bc65df80-6865-11ea-830b-99af9d0f9793.png)

## Version Info
Microsoft Python languageServer.0.5.31
VS Code Version: 1.43.0
VS Code Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Python Version: 3.8.2
OS: Windows_NT x64 10.0.18363

## Directory structure
```
WORKSPACE_ROOT.
│  main_root.py  #  unresolved import
│                        
├─.vscode                
│      settings.json     
│                        
└─src                    
    │  main_in_dir.py    # OK
    │                    
    └─module_dir         
            module.py    
```

.vscode/settings.json
```
{
    "python.linting.enabled": true,
    "python.autoComplete.extraPaths": [
        "./src"
    ]
}
```

"python.analysis.logLevel": "Trace"
OUTPUT / Python Language Server

[python_language_server_log.txt](https://github.com/microsoft/python-language-server/files/4341880/python_language_server_log.txt)

### I've read these solutions and tried them out

https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

https://github.com/Microsoft/vscode-python/issues/3977

https://github.com/microsoft/python-language-server/issues/1169

**Comment by jakebailey** [comment]
By default, we see a `src` path without `__init__.py` and assume that the user's code is rooted there. Your code seems to import `src.`, which does not follow that assumption. To disable this behavior, you can set:

```json
"python.analysis.autoSearchPaths": false
```

And with `extraPaths` unset, it will work,.

Note that importing `src.something` is highly unusual; most people treat `src` as an import root and import relative to that rather than directly. I have not yet seen a project that's doing `import src.something` yet, and other editors will have similar behavior making that same assumption.

#1615 #1789

**Comment by abarabakuhatsu** [comment]
Thank you, we have solved successfully

![2020-03-17_16h19_48](https://user-images.githubusercontent.com/43849035/76831692-2765e500-686b-11ea-9498-84c4888f8fbc.png)
