### ISSUE TITLE
${workspaceFolder} in extraPaths resolved unexpectedly

### ISSUE THREAD

**Issue by tpajenkamp-dspace** [microsoft/python-language-server#1974]
## Environment data

- Language Server version: 0.5.45.0   
- OS and version: Windows 10 1809
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.7 64-bit
- Visual Studio Code version: 1.43.2

## Expected behaviour
The variable `${workspaceFolder}` within the setting `"python.autoComplete.extraPaths"` is resolved to the correct workspace folder. For a project folder `C:/temp/myproject`, `${workspaceFolder}/sublibs` should be resolved to `C:/temp/myproject/sublibs` and `${workspaceFolder}/../sublibs` should be resolved to `C:/temp/sublibs`.

## Actual behaviour
The settings
```
{ "python.autoComplete.extraPaths": ["${workspaceFolder}/sublibs"] }
```
lead to missing auto complete for `sublibs`, the user search path in the output is
```
[Info  - 14:39:21] User search paths:
[Info  - 14:39:21]     C:\temp\myproject\${workspaceFolder}\sublibs
```

The settings
```
{ "python.autoComplete.extraPaths": ["${workspaceFolder}/../sublibs"] }
```
"fix" the problem, the user search path in the output is
```
[Info  - 14:41:42] User search paths:
[Info  - 14:41:42]     C:\temp\myproject\sublibs
```
However, the expected path is `C:\temp\sublibs`.

<!-- 
## Logs

Enable trace logging by adding "python.analysis.logLevel": "Trace" to your settings.json configuration file.

Adding this will cause a large amount of info to be printed to the Python output panel. This should not be left long term, as the performance impact of the logging is significant.

```
XXX
```-->

## Additional lnformation
Apparently, to get the correct workspace folder, I need to write `${workspaceFolder}/../`. If `${workspaceFolder}` is not followed by `..`, it is not resolved at all.

Of course, there is the workaround to use relative paths instead of this variable.
<!--
Note: If you think a GIF of what is happening would be helpful, consider tools like https://www.cockos.com/licecap/, https://github.com/phw/peek or https://www.screentogif.com/ .

```python
XXX
```-->

**Comment by jakebailey** [comment]
I'm pretty sure we don't support the `${workspaceFolder}` form at all (the whole "variables in config strings" thing is not consistent across editors/extensions/settings).

Does `.` work to refer to the workspace path?

**Comment by tpajenkamp-dspace** [comment]
Alright, thanks. A simple relative path works as expected.

The use of `${workspaceFolder}` in `extraPaths` for Visual Studio Code seems to be pretty common  on the internet and I am pretty sure it worked at some point in the past. Is it something the Python Extension should/could handle?

**Comment by jakebailey** [comment]
It was my impression originally that these variables were provided by the editor, and when we ask for the config, it does the replacement before returning the config to us. But, this doesn't appear to be true.

This may have worked in the past because we didn't allow the paths to be changed at runtime, and the extension would pass them directly at startup (so would do a "lookup" through its settings provider which would have handled the replacement). But in #1492, I changed to no longer needing that constraint and instead using the LSP to ask the client for the config.

The variables are implemented by the extension as documented here: https://code.visualstudio.com/docs/python/settings-reference#_predefined-variables

But, LSP is generally between the editor and the server without the extension in the middle (who was the one who created the variables), unless it opts to intercept and start replacing.

I'm not sure where exactly we'd want to modify things. The LS is supposed to be agnostic, but the variables are vscode-python specific. The immediate solution that comes to mind is to have the extension intercept all configuration messages and forcing a replacement, but that's pretty iffy.

**Comment by jakebailey** [comment]
Just remembered #1783.

**Comment by MikhailArkhipov** [comment]
Per `The LS is supposed to be agnostic, but the variables are vscode-python specific.`, LS should not be doing VSC-specific substitutions. There are other clients beside VSC. LS knows nothing about its client and cannot assume that `${}` variables have certain meaning.

**Comment by jakebailey** [comment]
I'd like to at least leave #1783 open; it's possible we'll want to handle these cases for the extension (and have some initialization option in the future to indicate we should do replacements).
