### ISSUE TITLE
Unresolved import for package installed in editable mode

### ISSUE THREAD

**Issue by sjrowlinson** [microsoft/python-language-server#1991]
## Environment data

- Language Server version: 0.5.45.0  
- OS and version: Kubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3 (Anaconda)
- VSCode version: 1.43.2

## Expected behaviour

Properly resolved imports of the package `finesse`.

## Actual behaviour

Unresolved imports for any sub-module of our package, whilst other packages (in the `site-packages` of the Conda environment for example) seem to be fine:

![unresolvedimports](https://user-images.githubusercontent.com/16781733/78928771-176fa880-7a99-11ea-9034-94e4b28ac7c6.png)

## Code Snippet / Additional lnformation

This package (`finesse`) was installed in editable mode, into the Conda environment being used, via

`pip install -e .`

if that makes any difference.

Note that I have already tried adding

```
"python.autoComplete.extraPaths": ["./finesse"],
```

to the `.vscode/settings.json` file in the project root. And I have also tried creating a `.env` file with

```
PYTHONPATH=./finesse
```

whilst adding

```
"python.envFile": "${workspaceFolder}/.env"
```

to the `settings.json`. Both of these give the same unresolved-imports warnings when importing from `finesse`.

**Comment by MikhailArkhipov** [comment]
Can you post initial LS output where it lists search paths. Thanks.

**Comment by sjrowlinson** [comment]
This is the LS output I get:

```
[Info  - 10:55:42] Analysis cache path: /home/sam/.cache/Microsoft/Python Language Server
[Info  - 10:55:42] Microsoft Python Language Server version 0.5.45.0
[Info  - 10:55:42] Workspace root: /home/sam/Documents/phd/finesse_development
[Info  - 10:55:42] GetCurrentSearchPaths /home/sam/anaconda3/envs/finesse3env/bin/python 
[Info  - 10:55:42] Interpreter search paths:
[Info  - 10:55:42]     /home/sam/anaconda3/envs/finesse3env/lib/python3.7
[Info  - 10:55:42]     /home/sam/anaconda3/envs/finesse3env/lib/python3.7/lib-dynload
[Info  - 10:55:42]     /home/sam/Documents/phd/pykat
[Info  - 10:55:42]     /home/sam/anaconda3/envs/finesse3env/lib/python3.7/site-packages
[Info  - 10:55:42]     /home/sam/Documents/programming_playground/testcython
[Info  - 10:55:42] User search paths:
[Info  - 10:55:42]     /home/sam/Documents/phd/finesse_development/finesse
[Info  - 10:55:44] Initializing for /home/sam/anaconda3/envs/finesse3env/bin/python
[Info  - 10:55:44] Analysis caching mode: None.
```

I guess the `finesse` dir being in the "User search paths" as opposed to the "Interpreter search paths" could indicate the problem here?

**Comment by jakebailey** [comment]
It should show up in the user search paths, as it's a subdirectory of the workspace ("user code"). The only difference is that doing an editable install will essentially automatically fill in an extraPath for that root (rather than requiring you to do it), i.e. what you already tried doing by hand.

The actual issue here is that by having `finesse` as an import root, any imports that look like `import finesse.components` are no longer valid. You'd have to do `import components` as we're looking in `finesse` for the modules.

The language server requires that each module have a unique name. By having `finesse` both as an import root (a search path added when doing an editable install) and a module (with submodules), we have to pick a single name and end up picking the first.

Technically, this is a duplicate of #1360. However, I'm a bit confused by this code layout. Are you expecting that both `import finesse.components` and `import components` work? Why would the editable install point to a directory _inside_ `finesse` rather than the directory in which it's contained?

**Comment by sjrowlinson** [comment]
Maybe I'm not clear on how the language server works, but I'd expect `import finesse` and `import finesse.X` where `X` is any sub-module (recursively deep) to be resolved properly from anywhere so long as the correct conda environment is active. Exactly that behaviour works fine for me on Windows for some reason, it just seems to be that on my Kubuntu machine (well, partition of the same machine) it does not resolve `finesse` nor any of its sub-modules from anywhere on the system in `vscode` when using the Microsoft language server.

Enabling jedi (on Kubuntu) does allow these imports to be resolved properly, but I was getting high CPU usage issues with that so wanted to switch to the Microsoft language server.

**Comment by jakebailey** [comment]
> Enabling jedi (on Kubuntu) does allow these imports to be resolved properly

Note that jedi has a pretty different import resolution mechanism than us (and python, in a way), as it tries to be forgiving and resolve imports even when they might not work. We're very strict about import resolution and err on the side of reporting something rather than trying to start looking in parent directories for a possible way to import things, even if it means over-erroring.

> Maybe I'm not clear on how the language server works, but I'd expect import finesse and import finesse.X where X is any sub-module (recursively deep) to be resolved properly from anywhere so long as the correct conda environment is active.

Yes, it should work, however the editable install appears to be marking the `finesse` directory _itself_ as an import root, not its parent. E.g, you have the import roots of:

```
/home/sam/Documents/phd/finesse_development         (workspace root)
/home/sam/Documents/phd/finesse_development/finesse (added by the editable install?)
```

Which with our import system (#1700) means that anything under `finesse` is "absolutely named" relative to that root.

If you're not expecting to import things directly from `finesse`, e.g. `import components`, rather than `import finesse.components`, then the editable installed path shouldn't be pointing to a directory inside `finesse`; it should be pointing to the directory above it which contains `finesse`.

I'd recommend uninstalling and installing the package and observing the difference between the paths the LS uses; I think the diff will show what I mean.

**Comment by jakebailey** [comment]
To give a more concrete example, imagine I have a module tree that looks like:

```
/home/jake/my_project/foo/bar/baz
```

I open `my_project` in VS Code. To get `baz`, I need to do `import foo.bar.baz`.

Now, imagine if I had configured `extraPaths` as `["./foo"]`. Now, what is `baz` "called"? I can feasibly import it as either `foo.bar.baz` or `bar.baz`, as both import roots "exist" and allow a path to the module. However, our analysis requires each module to have a single, unique name, so we end up only allowing `bar.baz`.

Replace `foo` with `finesse`, and I think that's the scenario you're in.

**Comment by sjrowlinson** [comment]
I see that makes sense, thanks for the information. Unfortunately when reinstalling the package I still see

```
/home/sam/Documents/phd/finesse_development/finesse
```

in the User search paths for some reason. Even if I just do `python setup.py develop -u` (to uninstall the package), I still see the above. Not sure how this is getting added to be honest, but I guess it is the culprit.

**Comment by jakebailey** [comment]
Yeah, if it's there even when you don't have the package editable-installed, then there's definitely something going else going on.

In the language server's download folder, there's a script which we use to get search paths. In your environment, can you run this script, like:

```
python -S -E /path/to/get_search_paths.py
```

And see what we classify that directory as? That way, we can see why it might be appearing.

**Comment by sjrowlinson** [comment]
Ok that directory was showing up as

```
/home/sam/Documents/phd/finesse_development/finesse|pth|
```

but I noticed that there was (somehow) a rogue

```
/home/sam/Documents/phd/finesse_development/finesse
```

line in the `easy-install.pth` file of this conda environment which I guess was causing the problem here. I've removed that now, re-installed the package in editable mode and the imports are now resolving properly.

Thanks for all the help again!
