### ISSUE TITLE
Updating Github releases

### ISSUE THREAD

**Issue by wbthomason** [microsoft/python-language-server#2081]
Hi! I'm wondering where to look for the latest releases for this project.

It seems that the latest Github release/tag is about a year old, at v0.2. However, looking at https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-linux-x64 indicates that v0.5.50 was released on 13 May 2020.

Would it be possible to start tagging releases on this repo as they're cut for https://pvsc.blob.core.windows.net/python-language-server-stable? This would be helpful for package maintainers who build from source, e.g. https://aur.archlinux.org/packages/microsoft-python-language-server/. 

If not, is there a recommended way to find the commit associated with a release on https://pvsc.blob.core.windows.net/python-language-server-stable?

Thanks!

**Comment by jakebailey** [comment]
It's important to note that we build and release from master, then select builds manually to push out via the blob storage. The tags do not reflect our release mechanism.

The version in the blobs isn't an actual release version, but a build number that "looks" like semver. Multiple blobs can point to the same commit as we change our build pipeline or rerun builds. These versions are intended purely for the VS Code extension's download and should not be used otherwise.

The tags are definitely out of date; we tagged 0.2 in order to preserve builds for Visual Studio; the tag is for a very old version we need to be able to refer to for reproducibility.

If you want to package this, you may want to instead package at a specific commit from master. A `-git` package I think makes the most sense for this repo where we aren't using tagging for our builds (at the moment).

**Comment by wbthomason** [comment]
Great, thanks! That’s helpful.

I would still personally benefit from up-to-date tagged releases here, but can absolutely just make a `-git` package. As such, I’ll close the issue as solved.

Thanks again!

**Comment by jakebailey** [comment]
Note that because of that tag, you may want to use the `r<NUMBER>.<HASH>-1` form for aesthetic reasons in a `-git` package, otherwise you'll get something like `0.2.r<NUMBER>.g<HASH>-1` which might be misleading. Entirely up to you, of course. I don't think it much matters so long as it works.

I know many Arch packages also use a specific commit and package a "stable" version that way, e.g. ttf-dejavu is currently at `2.37+18+g9b5d1b2f-1`, if you'd want a non `-git` version.

**Comment by wbthomason** [comment]
@jakebailey Thanks again for the information! I've made https://aur.archlinux.org/packages/microsoft-python-language-server-git, which should work for now.
