### ISSUE TITLE
unresolved-import after adding package to repository (Poetry/Venv)

### ISSUE THREAD

**Issue by Kyitrai** [microsoft/python-language-server#2085]
I'm using `poetry` for managing the environment and dependencies.

The behavior is that: any new packages added to the project (`poetry add <package>`) _after_ starting up VSCode are not found (`unresolved_import`). Running the code from the terminal inside VS Code or a detached terminal with the venv activated does not encounter any import errors.

![image](https://user-images.githubusercontent.com/6313344/85326904-450aa200-b48b-11ea-8e67-7991062b4a57.png)

Restarting VS Code entirely will resolve the problem after the language server re-initializes.

Poetry is set to instantiate the virtualenv in the project folder, so `.vscode/settings.json` has the setting `"python.pythonPath": ".venv/bin/python"`. The environment selection according to the status bar is also correct.

![image](https://user-images.githubusercontent.com/6313344/85327109-9fa3fe00-b48b-11ea-929e-7d9c43cb3b39.png)

I am using the Microsoft language server:
```json
{
    "python.jediEnabled": false,
    "python.languageServer": "Microsoft",
}
```

_Originally posted by @Kyitrai in https://github.com/microsoft/vscode-python/issues/11934#issuecomment-647727468_

**Comment by jakebailey** [comment]
This is currently expected behavior; to detect installed packages we need to watch files, and it proved more problematic than useful. You can enable this behavior manually with a setting: https://github.com/microsoft/python-language-server/blob/master/TROUBLESHOOTING.md#completions-do-not-update-andor-import-is-still-being-reported-as-unresolved-after-pip-install
