### ISSUE TITLE
Show warning for undeclared variables

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#242]
Also variables used before declaration

**Comment by MikhailArkhipov** [comment]
Adding sprint to we can start investigation

**Comment by jakebailey** [comment]
For the sake of writing it down, the plan is to add a new class to encapsulate "diagnostics" like undeclared variables, unknown imports, non-callables, etc, keep track of them in the analyzer, then later expose those with filtering, and past that, generate code actions from those diagnostics.

**Comment by jakebailey** [comment]
After going through everything, it turns out that `PythonAnalyzer._diagnostics` already basically encapsulates what we're looking for. There's already code in place for undeclared names _and_ code for missing imports (with an associated message). It should just need some tweaking to better define when diagnostics are created and filtered.

**Comment by jakebailey** [comment]
![image](https://user-images.githubusercontent.com/5341706/47123026-28d24e80-d22e-11e8-8a52-a0cc0de7134b.png)
