### ISSUE TITLE
How to debug incorrect analysis values being tracked?

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/python-language-server#293]
When analyzing some large project, I noticed, that a function parameter get assigned totally incorrect AnalysisValue. In addition to whatever expected parameter type there is, some other value is returned by `PythonAnalyzer.GetValues`. Upon inspecting Python code, I found a different parameter being assigned a value of that type. So somehow it gets mixed up.

Now I am wondering if there an easy way to track what causes analyzer to add that wrong value to analysis.

**Comment by MikhailArkhipov** [comment]
You may want to reduce amount of code to a small sample. Then set breakpoints in the DDG processing of statements and see what is getting assigned and when. However, if code in question comes from a library, then you want to look into `AstAnalysisWalker` since libraries are not processed by the main analyzer.
