### ISSUE TITLE
Completion item documentation property has null kind

### ISSUE THREAD

**Issue by johngalambos** [Microsoft/python-language-server#305]
Completion items are returning with documentation properties that look like this:

`"documentation": {
    "kind": null,
    "value": "None"
}`

The relevant spec is [here ](https://microsoft.github.io/language-server-protocol/specification) (Search for `MarkupContent`). According to the spec, `kind `should be one of `plaintext` or `markdown`.

Null kind values are causing problems with LanguageClient-neovim as described here https://github.com/autozimu/LanguageClient-neovim/issues/633#issuecomment-431575951:

**Comment by jakebailey** [comment]
The only place we don't explicitly choose between plaintext or markdown seems to be:

https://github.com/Microsoft/python-language-server/blob/18e25f19ca54e1b0b879038ca2cb387563b84ecd/src/LanguageServer/Impl/Implementation/CompletionAnalysis.cs#L803-L814

The kind being set comes from `initializationOptions.displayOptions`; see here in the VS Code extension: https://github.com/Microsoft/vscode-python/blob/efa175ca29476469136c07c783f6cbd28a976ff0/src/client/activation/languageServer/languageServer.ts#L280-L286

You should be able to mirror the options set by the VS Code extension in the `settings.json` mentioned in the neovim issue as a quick fix. There are probably other things being set there that are good to have. (Those Sublime instructions were contributed from someone outside our team and we haven't really tested them, nor in other editors.)

On our end we could add `?? MarkupKind.PlainText` to the PLS code I linked above, but I'm honestly surprised that we're not using `TextDocumentClientCapabilities .completion.completionItem.documentationFormat` instead of a custom option.

**Comment by johngalambos** [comment]
Thanks! Adding the `initializationOptions.displayOptions` you suggested to the settings file works perfectly to get the values for kind. Still having some issues parsing the completion items--those VS Code settings should hopefully put me on the right track though.
