### ISSUE TITLE
Types from typings are shown as base types

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/python-language-server#329]
In
```python
Vector = List[float]

def scale(scalar: float, vector: Vector) -> Vector:
    return [scalar * num for num in vector]

new_vector = scale(2.0, [1.0, -4.2, 5.4])
```

`scale` is shown as 

![image](https://user-images.githubusercontent.com/12820357/47823296-e24c1c00-dd24-11e8-83dc-28d9bac7d15d.png)

PyCharm
![image](https://user-images.githubusercontent.com/12820357/47823234-884b5680-dd24-11e8-8b47-dde39f5ec399.png)

Or should we actually show `Vector` as argument type rather than base?

**Comment by jakebailey** [comment]
Personally, I'd lean slightly toward showing `Vector`. When you go to use that parameter (inside the function) or the return value, then completion would be able to show you more.

The only trouble is that in this instance `Vector` might be less helpful, since in your example you're passing in the concrete `list[float]` which is a valid thing to do. Also, if I were to write something like:

```python
if some_condition:
	out = v
else:
	out = scale(3.141, v)
```

Even through `v` and `out` are compatible types, then we might run into trouble saying the type of `out` is `Vector` and `list[float]`. Depending on how generics goes, then there's also the differentiation of `list[float]` and `List[float]` to deal with...

**Comment by MikhailArkhipov** [comment]
New code does it right.

![image](https://user-images.githubusercontent.com/12820357/51959797-e7dffd80-240a-11e9-99f4-5e56b3dd8463.png)

**Comment by MikhailArkhipov** [comment]
Tooltips got reworked, closing
