### ISSUE TITLE
Language server not running under Windows 7 SP1

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#332]
Microsoft/vscode-python#3112

https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md seems to suggest it should work, but the OP says it isn't even after installing .NET Core.

**Comment by MikhailArkhipov** [comment]
Server runs on .NET Core 2.1.
https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore21

For **Windows 8.1 and earlier versions**, or Windows Server 2012 R2 and earlier versions:
**Make sure that your Windows installation is up-to-date and includes KB2999226**, which can be installed through Windows Update. If you don't have this update installed, you'll see an error like the following when you launch a .NET Core application: The program can't start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

For **Windows 7** or Windows Server 2008 R2:
**In addition to KB2999226, make sure you also have KB2533623 installed**. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: **The library hostfxr.dll was found, but loading it from C:<path_to_app>\hostfxr.dll failed**.

**Comment by MikhailArkhipov** [comment]
Parent is closed
