### ISSUE TITLE
Function parameter with a default of `None` is saying that's also the type

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#375]
Microsoft/vscode-python#3244

```python
def spam(x=None):
    pass

spam()
```
That ends up saying that `spam()` has an argument of `x: None=None` which is technically correct based on the default value, but `None` is so often used as placeholder to mean "no argument provided" that assuming the type is `None` is too strict in most cases.

**Comment by jakebailey** [comment]
I think it might be a good idea to not show `None` at all for the type. Our current implementation collects info from all calls to fill things in when types aren't provided, so if I change that function a little and pass in a value, you can see that the signature will change:

![image](https://user-images.githubusercontent.com/5341706/48234238-adb41200-e36d-11e8-93e9-f0faf9db913a.png)

I've just found some goofyness when you go to use `Optional`, so that's not a super great option in the current PLS implementation, unfortunately. I'll file a bug for that separately, though.

**Comment by jakebailey** [comment]
Ah, I don't mean to remove None altogether, just to not display it in the user-visible string. We'd still want None to have for generating that return type, for example, since it can technically return None.

**Comment by jakebailey** [comment]
Elaborating:

In the future, we want to stop doing "collect all calls and union types" method in favor of just walking the function's AST including type hints. In that case with this function, the user hasn't explicitly written that it's supposed to be Any or some other type, so arguably, "None" may be the best we can do. Especially in the original case where the function is just `pass` with no uses of the argument.

A case where a function has a default of None and no type hint might be the one special case we want to have, since it's so common in current code.

**Comment by jakebailey** [comment]
I'm going to close this, since the new language server outputs: 

![image](https://user-images.githubusercontent.com/5341706/52744293-23dd9b80-2f91-11e9-8cbe-f00ab556556f.png)

As for my example with:

```python
def f(x=None):
    return x

f("4")
```

We're treating `x` to be of type `NoneType` (as I suspected would occur in https://github.com/Microsoft/python-language-server/issues/375#issuecomment-437208649), so `f("4").` isn't going to show completion for strings. I've made #604 to see about potentially changing the behavior `x=None` to emulate `x=Optional[_T]` (where `_T` is some generated type) or similar to better support unannotated code.
