### ISSUE TITLE
Assignments don't always change variable types

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#428]
![image](https://user-images.githubusercontent.com/5341706/48811821-4fc7e880-ece4-11e8-96dc-2e12ad1609f0.png)

Here, `a` is initially a list of strings, but after line 4, it should be known to be a list of ints.

Found in #334.

**Comment by MikhailArkhipov** [comment]
This is not currently possible as analysis is static. Code does not track type by location. Thus, at best, variable will have two types. In order to make this work the engine either has to eval code to the completion point (JavaScript editor used to do this) or types attached to variable need to have 'applicable spans' associated with them.

**Comment by MikhailArkhipov** [comment]
It would be a fundamental and pretty expensive change.

**Comment by MikhailArkhipov** [comment]
New analysis uses the last assignment. Location tracking folding into #682
