### ISSUE TITLE
Completions for Tensorflow 1.12.0 missing

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#453]
Microsoft/vscode-python#3515

The OP says Jedi is fine and both Jedi and LS worked fine under 1.11.0.

**Comment by jakebailey** [comment]
Seems like we got worse since #285.

**Comment by jakebailey** [comment]
I just saw the edit about the version info. If it's actually broken from 1.11 to 1.12, then I would have guessed that there was some code change there which uses some feature we don't completely support.

But looking at their repo, I don't believe that to be the case. There haven't been any changes to the `nn` module since August, which is before even 1.11 was released.

**Comment by ericsnowcurrently** [comment]
Per https://github.com/Microsoft/vscode-python/issues/5141, this still seems to be a problem.

**Comment by jakebailey** [comment]
I fixed this in #881; the stable channel does not have the fix yet. It be tested in the beta channel.

**Comment by jakebailey** [comment]
![image](https://user-images.githubusercontent.com/5341706/56161946-b1347080-5f7f-11e9-8e3e-49d4c94ea205.png)

**Comment by ericsnowcurrently** [comment]
ah, thanks
