### ISSUE TITLE
No auto-completion for pybullet

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#482]
@Arthur-sky commented on [Sat Dec 08 2018](https://github.com/Microsoft/vscode-python/issues/3599)

## Environment data

- VS Code version: 1.30.0-insider
- Extension version (available under the Extensions sidebar): 2018.11.0 
- OS and version: ubuntu
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.7
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
- Relevant/affected Python packages and their versions: pybullet

## Expected behaviour

code hint should work

## Actual behaviour

when pybullet is imported, code hint does not work;

## Steps to reproduce:
1. install the enviroment, config the virtualenv pythonpath
2. in a new file, add: import pybullet as pb
3. the code hint does not work, even for other package

---

@brettcannon commented on [Mon Dec 10 2018](https://github.com/Microsoft/vscode-python/issues/3599#issuecomment-445932361)

What do you mean by "code hint"? Do you mean auto-complete/IntelliSense?

---

@brettcannon commented on [Mon Dec 10 2018](https://github.com/Microsoft/vscode-python/issues/3599#issuecomment-445932496)

And what is in your Output panel?

---

@Arthur-sky commented on [Tue Dec 11 2018](https://github.com/Microsoft/vscode-python/issues/3599#issuecomment-446149453)

@brettcannon 
1. yes, "code hint" means auto-complete/IntelliSense.
2. the code functions well, only without auto-complete while coding.

**Comment by jakebailey** [comment]
I can't reproduce this, at least not after #546.

![image](https://user-images.githubusercontent.com/5341706/52462412-d5ab4100-2b27-11e9-99c1-592a31bcb53b.png)

Maybe the completion was failing because the language server had silently crashed (since this issue is before my bugfixes in the old analyzer).

Either way, completion for pybullet seems to work, though it's a compiled library so the quality of the analysis depends heavily on what we can scrape.
