### ISSUE TITLE
PLS doesn't detect changes to PYTHONPATH in .env file

### ISSUE THREAD

**Issue by erictraut** [Microsoft/python-language-server#504]
If I define a PYTHONPATH environment variable in a workspace-level ".env" file, the PLS correctly uses the defined path as part of its import resolution. However, if I modify the ".env" file, the PLS doesn't correctly pick up the change. Closing and opening the IDE solves the problem. It would be preferable if the PLS or the VSCode python extension installed a watcher on the ".env" file and handled changes appropriately.

**Comment by jakebailey** [comment]
The language server is passed search paths by the extension on startup and at configuration change. We don't do any sort of `.env` parsing, so that must be happening in the extension.

I'm assuming the documentation you saw was: https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file

Which I think actually predates the language server. You may want to open an issue on the extension if its contents are not being monitored and updated. (I'd think that it'd also affect the extension when used with Jedi as well.)

**Comment by erictraut** [comment]
OK, thanks. I've filed the following bug in the Microsoft/vscode-python project:
https://github.com/Microsoft/vscode-python/issues/3805
