### ISSUE TITLE
PLS doesn't handle changes to python.autoComplete.extraPaths setting

### ISSUE THREAD

**Issue by erictraut** [microsoft/python-language-server#507]
If I define one or more entries in the `python.autoComplete.extraPaths` setting, the PLS correctly uses the defined path(s) as part of its import resolution. However, if I modify the setting, the PLS doesn't correctly pick up the change. Closing and opening the IDE solves the problem.

I'm not sure if this is a problem with the vscode python extension or the PLS.

**Comment by AlexanderSher** [comment]
LS receives `extraPaths` as part of `PythonInitializationOptions.searchPaths` when it is started. @MikhailArkhipov , do you know if LS is restarted when this parameter is changed?

**Comment by MikhailArkhipov** [comment]
It didn't change AFAIK.
https://github.com/Microsoft/vscode-python/blob/master/src/client/activation/languageServer/languageServer.ts#L246-253
```ts
        let searchPaths = interpreterData ? interpreterData.searchPaths.split(path.delimiter) : [];
        const settings = this.configuration.getSettings();
        if (settings.autoComplete) {
            const extraPaths = settings.autoComplete.extraPaths;
            if (extraPaths && extraPaths.length > 0) {
                searchPaths.push(...extraPaths);
            }
        }
```

**Comment by DonJayamanne** [comment]
Is it not possible for the LS to react to changes to this setting if it was somehow propagated to LS.
Ie can LS react to changes without having to restart the LS.

**Comment by MikhailArkhipov** [comment]
May be part of #1213

**Comment by jakebailey** [comment]
With #1289 merged, this could now be possible. Paths are now resolved later at the first `ReloadAsync`, versus in the initialization. Since the extension has been starting the language server with PYTHONPATH set, we could stop accepting `searchPaths` in our initialization options, then do the combining of PYTHONPATH/extraPaths together ourselves. Doing this would allow us to redo that work when we see the config change.

But we'd need to decide whether or not `python.autoComplete.extraPaths` is the actual configuration name we want to give this. I expect we want settings under `python.analysis` instead, with some more granularity to let people pick and choose which paths go where (instead of a big list).

**Comment by Jma353** [comment]
Moving away from `searchPaths` and towards config-driven `extraPaths` that reacts to changes in the config would be awesome!

**Comment by jakebailey** [comment]
I'm going to close this in favor of #1388. This should now be doable (as previously said). The setting name is likely to change, as it's a relic.
