### ISSUE TITLE
Parameterized types of generic classes sometimes shared between class instances

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#590]
In the below, both `intval` and `strval` come to be `int`, even though hovering over `boxedint` and `boxedstr` show `Box[int]` and `Box[str]` respectively.

```python
from typing import TypeVar, Generic

_T = TypeVar("_T")

class Box(Generic[_T]):
    def __init__(self, v: _T):
        self.v = v
    
    def get(self) -> _T:
        return self.v


boxedint = Box(1234)
intval = boxedint.get()

boxedstr = Box("foo")
strval = boxedstr.get()
```

**Comment by MikhailArkhipov** [comment]
Most probably relates to the `-> _T` tooltip on `get()`

**Comment by MikhailArkhipov** [comment]
OK, got it. The problem was that when specific type was created from template, it reused same method type instances since creation of the specific type just added references and then setting the result type set it to all specific types and the template.

Better solution is to remember supplied type arguments in the specific type (i.e. what the type was created from) and have function determine return type dynamically from them. This way we don't need to clone function type for the specific class. It is also provides better encapsulation since class type then knows less about its method type innards.
