### ISSUE TITLE
Sometimes no analysis for pip installed libraries

### ISSUE THREAD

**Issue by jakebailey** [Microsoft/python-language-server#601]
Some libraries installed via pip such as `numpy` end up with an message like:

```
[Info  - 12:17:31 PM] Import not found: numpy
```

And no analysis info.

Sometimes the analysis gets hung up on analyzing some pip related libraries and appears to not proceed, but that may be another issue.

**Comment by MikhailArkhipov** [comment]
To verify with the dependency handling. Current imports code is not bullet proof.

**Comment by jakebailey** [comment]
Also on a Django project:

```
Analysis queued: cool
[Info  - 1:37:08 PM] Import not found: django.db
Import:  django.db c:\Users\jabaile\Desktop\djangoo\venv\lib\site-packages\django\db\__init__.py 
Analysis queued: django.db
[Info  - 1:37:08 PM] Import not found: django.core
Import:  django.core c:\Users\jabaile\Desktop\djangoo\venv\lib\site-packages\django\core\__init__.py 
```

**Comment by MikhailArkhipov** [comment]
I found where 'import not found' is coming from. It is red herring - typeshed resolution happens to report this way that the stub is not found. Fixed that with a better message. Secondary issue, which is, in fact, caused import to start looking for a stub is that file inside workspace was being considered library rather than user code.

**Comment by MikhailArkhipov** [comment]
There is recursive import in `scikit-learn`, opening `_k_means` eventually leads to `spectral.py` which again imports `from .k_means_ import k_means`. Current import/dependency resolution does not handle this reliably.
