### ISSUE TITLE
colorization does not look right for dict repr's

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/python-language-server#725]
![image](https://user-images.githubusercontent.com/3840081/54062327-34f98100-41ba-11e9-9412-e7241bf58785.png)

**Comment by jakebailey** [comment]
Colorization is not under the language server's control; the look of those are handled by VS Code / the extension's shipped TextMate profile. Since TextMate colorization is essentially regex, I think that is being detected as an fstring or a format string.

You probably need to file a bug on vscode itself to get them to do something with this file: https://github.com/Microsoft/vscode/blob/master/extensions/python/syntaxes/MagicPython.tmLanguage.json
