### ISSUE TITLE
Go to reference is not working for a relative import *

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/python-language-server#730]
@tmab2003 commented on [Mon Mar 11 2019](https://github.com/Microsoft/vscode-python/issues/4706)

I have the following in my main module: `file_1`

`#file_1.py`
`from ...scenarios import *`
`module_1.method_1()`

Where I have a module called 'module_1' in the `scenarios` package which has a method defined 'method_1'

and I cannot seem to F12 in to any of these modules or methods.

**Comment by MikhailArkhipov** [comment]
#699

**Comment by MikhailArkhipov** [comment]
@tmab2003 - could you please list structure of your workspace. Is `scenarios` part of the workspace? Have you tried LS 0.2 from the beta channel?
```json
"python.analysis.downloadChannel": "beta"
```

**Comment by tmab2003** [comment]
@MikhailArkhipov - I added that setting string to the settings.json file for my workspace - will that be adequate?

`{
    "python.pythonPath": "C:\\Python37\\python.exe",
    "python.analysis.downloadChannel": "beta"
}`

The structure is as follows:

../RootFolderForProject/Folder_1/Folder_2/Folder_3/Folder_4/scenarios/module_1.py

file_1 which is here:

../RootFolderForProject/Folder_1/Folder_2/Folder_3/Folder_4/Folder_5/Folder_6/file_1.py

which is why I have to import with three dots, from ...scenarios import * (which should import all modules_*.py)..

**Comment by MikhailArkhipov** [comment]
I assume you are opening `RootFolderForProject` as workspace?
Does the code work in Python console? I am asking since `...` does not necessarily mean three folders up per https://www.python.org/dev/peps/pep-0328/ ie "Two or more leading dots give a relative import to the _parent(s) of the current package_, one level per dot after the first. " .

**Comment by tmab2003** [comment]
Yes RootFolderForProject is the workspace folder.

The code works and other Python IDEs seem to navigate this just fine. 
In Eclipse (Pydev), I believe I added the workspace directory as a Source Folder (don't remember if this was absolutely necessary for the relative imports to work..)

**Comment by tmab2003** [comment]
@AlexanderSher , @MikhailArkhipov  - I am not sure if the issue was fixed...but the relative import doesn't seem to be working for  relative paths with `...` yet. I am on the latest LS as of now.
Microsoft Python Language Server version 0.2.43.0

**Comment by jakebailey** [comment]
Are you saying the imports don't work, or go to references? The latter is not in the language server until #819 is merged.

**Comment by tmab2003** [comment]
Go to references indeed. Thanks for the update @jakebailey!
