### ISSUE TITLE
Unconditionally reading InitializeParams

### ISSUE THREAD

**Issue by ryanp97** [microsoft/python-language-server#751]
In the following code-snippet, the `InitializeParams.initializationOptions` is being unconditionally read despite it being allowed to be `null`, causing errors when setting this language server up with vim-lsc. 

https://github.com/Microsoft/python-language-server/blob/d63a6463fb14144e390ace912f42faaeb372fc48/src/LanguageServer/Impl/Implementation/Server.cs#L100-L150

**Comment by jakebailey** [comment]
At the moment, these options need to be set, otherwise the language server isn't going to be functional. Perhaps it shouldn't crash, but if you want it to work you have to specify the settings. I'm working on cleaning up the initialization and defaults (#720, #608, #678, #469), but I don't think we're going to get to a point quite yet where that value will be allowed to be `null` and the LS still start into a good state.

**Comment by ryanp97** [comment]
Is it possible to have it default to some non-null, blank object here so that it follows LSP?

**Comment by jakebailey** [comment]
That's what I was saying above; we need to define defaults, but there are other configuration changes and decisions that need to happen before that is immediately possible.

**Comment by MikhailArkhipov** [comment]
Is this still applicable since items above are now closed except #469.
