### ISSUE TITLE
Go to definition does not work in new LS

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/python-language-server#850]
@DonJayamanne commented on [Sun Mar 31 2019](https://github.com/Microsoft/vscode-python/issues/5037)

## Works with Jedi but not LS

A picture says a thousand words...
* Mac
* Python 3.7
* Use [behave](https://github.com/behave/behave) repo
![gotodef](https://user-images.githubusercontent.com/1948812/55300533-c9878580-53ec-11e9-94d0-d82754409046.gif)

**Comment by MikhailArkhipov** [comment]
@DonJayamanne - still broken? There were a number of fixes since.

**Comment by amittleider** [comment]
I experience this issue often in my code base. I also experience a different, but related issue where "Go to definition" will incorrectly move me to the `import` statement at the top of the file, instead of actually jumping to the definition. Here's a gif:

![ms_language_server_go_to_def](https://user-images.githubusercontent.com/1625951/58559204-dd9c0780-8222-11e9-9bed-cebbfa5b5504.gif)

**Comment by DonJayamanne** [comment]
@MikhailArkhipov

It works for me now, apologies for the delay.

**Comment by MikhailArkhipov** [comment]
@amittleider - this is by design. First navigation takes you where variable is first defined in the current file, then navigation from import takes you to the library. If you prefer different behavior, please file a separate issue. I guess it would be a setting controlling if the navigation should be direct.

**Comment by amittleider** [comment]
Hi @MikhailArkhipov , thanks for the reply. I have opened a new issue here: https://github.com/microsoft/python-language-server/issues/1138 .
